NUM_KEY_VALUE_PAIRS=100
NUM_NODES=3
KEY_SIZE=24
VALUE_SIZE=4096
TOTAL_OPERATIONS=1000
OP_FILE="\"operations.txt\""
DATASET_FILE="\"./dataset.txt\""

# enum DistributionType {
#     RANDOM_DISTRIBUTION,
#     PARTITIONED_DISTRIBUTION,
#     ZIPFIAN_DISTRIBUTION,
#     ZIPFIAN_PARTITIONED_DISTRIBUTION,
#	  SINGLE_NODE_HOT_KEYS
# };
DISTRIBUTION_TYPE = SINGLE_NODE_HOT_KEYS

# Key Distribution setting
HOT_KEY_PERCENTAGE = 0.20
HOT_KEY_ACCESS_PERCENTAGE = 0.80