// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: packet.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000002
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(d1a6b028d23ecc19);
enum class ResponseType_d1a6b028d23ecc19: uint16_t {
  OK,
  INVALID,
};
CAPNP_DECLARE_ENUM(ResponseType, d1a6b028d23ecc19);
CAPNP_DECLARE_SCHEMA(eea585a8e0273b7b);
CAPNP_DECLARE_SCHEMA(e49824f5cff34d68);
CAPNP_DECLARE_SCHEMA(a51a80a5d0621603);
CAPNP_DECLARE_SCHEMA(9c293df3f2a02a07);
CAPNP_DECLARE_SCHEMA(eb67a0eae928bb61);
CAPNP_DECLARE_SCHEMA(d8f2d86285d59919);
CAPNP_DECLARE_SCHEMA(d92927b00c6d5396);
CAPNP_DECLARE_SCHEMA(9736b56e253cba13);
CAPNP_DECLARE_SCHEMA(d74e917dbcd881cb);
CAPNP_DECLARE_SCHEMA(f90a05fd026809ad);
CAPNP_DECLARE_SCHEMA(b36ecfe36db7d4ef);
CAPNP_DECLARE_SCHEMA(a9a1635b25f07a7b);
CAPNP_DECLARE_SCHEMA(9cc4c008dd1d858e);

}  // namespace schemas
}  // namespace capnp


typedef ::capnp::schemas::ResponseType_d1a6b028d23ecc19 ResponseType;

struct PutRequest {
  PutRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(eea585a8e0273b7b, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct PutResponse {
  PutResponse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e49824f5cff34d68, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct GetRequest {
  GetRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a51a80a5d0621603, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct GetResponse {
  GetResponse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9c293df3f2a02a07, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct RdmaSetupRequest {
  RdmaSetupRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(eb67a0eae928bb61, 3, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct RdmaSetupResponse {
  RdmaSetupResponse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d8f2d86285d59919, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ClientSyncRequest {
  ClientSyncRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d92927b00c6d5396, 2, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ClientSyncResponse {
  ClientSyncResponse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9736b56e253cba13, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct SingletonPutRequest {
  SingletonPutRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d74e917dbcd881cb, 2, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct DeleteRequest {
  DeleteRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f90a05fd026809ad, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Packet {
  Packet() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  struct Data;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b36ecfe36db7d4ef, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Packet::Data {
  Data() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    PUT_REQUEST,
    PUT_RESPONSE,
    GET_REQUEST,
    GET_RESPONSE,
    RDMA_SETUP_REQUEST,
    RDMA_SETUP_RESPONSE,
    CLIENT_SYNC_REQUEST,
    CLIENT_SYNC_RESPONSE,
    SINGLETON_PUT_REQUEST,
    DELETE_REQUEST,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a9a1635b25f07a7b, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Packets {
  Packets() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(9cc4c008dd1d858e, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class PutRequest::Reader {
public:
  typedef PutRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasKey() const;
  inline  ::capnp::Text::Reader getKey() const;

  inline bool hasValue() const;
  inline  ::capnp::Text::Reader getValue() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PutRequest::Builder {
public:
  typedef PutRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasKey();
  inline  ::capnp::Text::Builder getKey();
  inline void setKey( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initKey(unsigned int size);
  inline void adoptKey(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownKey();

  inline bool hasValue();
  inline  ::capnp::Text::Builder getValue();
  inline void setValue( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initValue(unsigned int size);
  inline void adoptValue(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownValue();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PutRequest::Pipeline {
public:
  typedef PutRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class PutResponse::Reader {
public:
  typedef PutResponse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PutResponse::Builder {
public:
  typedef PutResponse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse();
  inline void setResponse( ::ResponseType value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PutResponse::Pipeline {
public:
  typedef PutResponse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class GetRequest::Reader {
public:
  typedef GetRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasKey() const;
  inline  ::capnp::Text::Reader getKey() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class GetRequest::Builder {
public:
  typedef GetRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasKey();
  inline  ::capnp::Text::Builder getKey();
  inline void setKey( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initKey(unsigned int size);
  inline void adoptKey(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownKey();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class GetRequest::Pipeline {
public:
  typedef GetRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class GetResponse::Reader {
public:
  typedef GetResponse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse() const;

  inline bool hasValue() const;
  inline  ::capnp::Text::Reader getValue() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class GetResponse::Builder {
public:
  typedef GetResponse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse();
  inline void setResponse( ::ResponseType value);

  inline bool hasValue();
  inline  ::capnp::Text::Builder getValue();
  inline void setValue( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initValue(unsigned int size);
  inline void adoptValue(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownValue();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class GetResponse::Pipeline {
public:
  typedef GetResponse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class RdmaSetupRequest::Reader {
public:
  typedef RdmaSetupRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getMachineIndex() const;

  inline  ::uint64_t getStartAddress() const;

  inline  ::uint64_t getSize() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RdmaSetupRequest::Builder {
public:
  typedef RdmaSetupRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getMachineIndex();
  inline void setMachineIndex( ::uint64_t value);

  inline  ::uint64_t getStartAddress();
  inline void setStartAddress( ::uint64_t value);

  inline  ::uint64_t getSize();
  inline void setSize( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RdmaSetupRequest::Pipeline {
public:
  typedef RdmaSetupRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class RdmaSetupResponse::Reader {
public:
  typedef RdmaSetupResponse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RdmaSetupResponse::Builder {
public:
  typedef RdmaSetupResponse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse();
  inline void setResponse( ::ResponseType value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RdmaSetupResponse::Pipeline {
public:
  typedef RdmaSetupResponse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ClientSyncRequest::Reader {
public:
  typedef ClientSyncRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse() const;

  inline  ::uint64_t getIndex() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ClientSyncRequest::Builder {
public:
  typedef ClientSyncRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse();
  inline void setResponse( ::ResponseType value);

  inline  ::uint64_t getIndex();
  inline void setIndex( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ClientSyncRequest::Pipeline {
public:
  typedef ClientSyncRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ClientSyncResponse::Reader {
public:
  typedef ClientSyncResponse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ClientSyncResponse::Builder {
public:
  typedef ClientSyncResponse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::ResponseType getResponse();
  inline void setResponse( ::ResponseType value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ClientSyncResponse::Pipeline {
public:
  typedef ClientSyncResponse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class SingletonPutRequest::Reader {
public:
  typedef SingletonPutRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasKey() const;
  inline  ::capnp::Text::Reader getKey() const;

  inline bool hasValue() const;
  inline  ::capnp::Text::Reader getValue() const;

  inline bool getSingleton() const;

  inline  ::uint64_t getForwardCount() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class SingletonPutRequest::Builder {
public:
  typedef SingletonPutRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasKey();
  inline  ::capnp::Text::Builder getKey();
  inline void setKey( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initKey(unsigned int size);
  inline void adoptKey(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownKey();

  inline bool hasValue();
  inline  ::capnp::Text::Builder getValue();
  inline void setValue( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initValue(unsigned int size);
  inline void adoptValue(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownValue();

  inline bool getSingleton();
  inline void setSingleton(bool value);

  inline  ::uint64_t getForwardCount();
  inline void setForwardCount( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class SingletonPutRequest::Pipeline {
public:
  typedef SingletonPutRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class DeleteRequest::Reader {
public:
  typedef DeleteRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasKey() const;
  inline  ::capnp::Text::Reader getKey() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class DeleteRequest::Builder {
public:
  typedef DeleteRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasKey();
  inline  ::capnp::Text::Builder getKey();
  inline void setKey( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initKey(unsigned int size);
  inline void adoptKey(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownKey();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class DeleteRequest::Pipeline {
public:
  typedef DeleteRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Packet::Reader {
public:
  typedef Packet Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline typename Data::Reader getData() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Packet::Builder {
public:
  typedef Packet Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline typename Data::Builder getData();
  inline typename Data::Builder initData();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Packet::Pipeline {
public:
  typedef Packet Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline typename Data::Pipeline getData();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Packet::Data::Reader {
public:
  typedef Data Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isPutRequest() const;
  inline bool hasPutRequest() const;
  inline  ::PutRequest::Reader getPutRequest() const;

  inline bool isPutResponse() const;
  inline bool hasPutResponse() const;
  inline  ::PutResponse::Reader getPutResponse() const;

  inline bool isGetRequest() const;
  inline bool hasGetRequest() const;
  inline  ::GetRequest::Reader getGetRequest() const;

  inline bool isGetResponse() const;
  inline bool hasGetResponse() const;
  inline  ::GetResponse::Reader getGetResponse() const;

  inline bool isRdmaSetupRequest() const;
  inline bool hasRdmaSetupRequest() const;
  inline  ::RdmaSetupRequest::Reader getRdmaSetupRequest() const;

  inline bool isRdmaSetupResponse() const;
  inline bool hasRdmaSetupResponse() const;
  inline  ::RdmaSetupResponse::Reader getRdmaSetupResponse() const;

  inline bool isClientSyncRequest() const;
  inline bool hasClientSyncRequest() const;
  inline  ::ClientSyncRequest::Reader getClientSyncRequest() const;

  inline bool isClientSyncResponse() const;
  inline bool hasClientSyncResponse() const;
  inline  ::ClientSyncResponse::Reader getClientSyncResponse() const;

  inline bool isSingletonPutRequest() const;
  inline bool hasSingletonPutRequest() const;
  inline  ::SingletonPutRequest::Reader getSingletonPutRequest() const;

  inline bool isDeleteRequest() const;
  inline bool hasDeleteRequest() const;
  inline  ::DeleteRequest::Reader getDeleteRequest() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Packet::Data::Builder {
public:
  typedef Data Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isPutRequest();
  inline bool hasPutRequest();
  inline  ::PutRequest::Builder getPutRequest();
  inline void setPutRequest( ::PutRequest::Reader value);
  inline  ::PutRequest::Builder initPutRequest();
  inline void adoptPutRequest(::capnp::Orphan< ::PutRequest>&& value);
  inline ::capnp::Orphan< ::PutRequest> disownPutRequest();

  inline bool isPutResponse();
  inline bool hasPutResponse();
  inline  ::PutResponse::Builder getPutResponse();
  inline void setPutResponse( ::PutResponse::Reader value);
  inline  ::PutResponse::Builder initPutResponse();
  inline void adoptPutResponse(::capnp::Orphan< ::PutResponse>&& value);
  inline ::capnp::Orphan< ::PutResponse> disownPutResponse();

  inline bool isGetRequest();
  inline bool hasGetRequest();
  inline  ::GetRequest::Builder getGetRequest();
  inline void setGetRequest( ::GetRequest::Reader value);
  inline  ::GetRequest::Builder initGetRequest();
  inline void adoptGetRequest(::capnp::Orphan< ::GetRequest>&& value);
  inline ::capnp::Orphan< ::GetRequest> disownGetRequest();

  inline bool isGetResponse();
  inline bool hasGetResponse();
  inline  ::GetResponse::Builder getGetResponse();
  inline void setGetResponse( ::GetResponse::Reader value);
  inline  ::GetResponse::Builder initGetResponse();
  inline void adoptGetResponse(::capnp::Orphan< ::GetResponse>&& value);
  inline ::capnp::Orphan< ::GetResponse> disownGetResponse();

  inline bool isRdmaSetupRequest();
  inline bool hasRdmaSetupRequest();
  inline  ::RdmaSetupRequest::Builder getRdmaSetupRequest();
  inline void setRdmaSetupRequest( ::RdmaSetupRequest::Reader value);
  inline  ::RdmaSetupRequest::Builder initRdmaSetupRequest();
  inline void adoptRdmaSetupRequest(::capnp::Orphan< ::RdmaSetupRequest>&& value);
  inline ::capnp::Orphan< ::RdmaSetupRequest> disownRdmaSetupRequest();

  inline bool isRdmaSetupResponse();
  inline bool hasRdmaSetupResponse();
  inline  ::RdmaSetupResponse::Builder getRdmaSetupResponse();
  inline void setRdmaSetupResponse( ::RdmaSetupResponse::Reader value);
  inline  ::RdmaSetupResponse::Builder initRdmaSetupResponse();
  inline void adoptRdmaSetupResponse(::capnp::Orphan< ::RdmaSetupResponse>&& value);
  inline ::capnp::Orphan< ::RdmaSetupResponse> disownRdmaSetupResponse();

  inline bool isClientSyncRequest();
  inline bool hasClientSyncRequest();
  inline  ::ClientSyncRequest::Builder getClientSyncRequest();
  inline void setClientSyncRequest( ::ClientSyncRequest::Reader value);
  inline  ::ClientSyncRequest::Builder initClientSyncRequest();
  inline void adoptClientSyncRequest(::capnp::Orphan< ::ClientSyncRequest>&& value);
  inline ::capnp::Orphan< ::ClientSyncRequest> disownClientSyncRequest();

  inline bool isClientSyncResponse();
  inline bool hasClientSyncResponse();
  inline  ::ClientSyncResponse::Builder getClientSyncResponse();
  inline void setClientSyncResponse( ::ClientSyncResponse::Reader value);
  inline  ::ClientSyncResponse::Builder initClientSyncResponse();
  inline void adoptClientSyncResponse(::capnp::Orphan< ::ClientSyncResponse>&& value);
  inline ::capnp::Orphan< ::ClientSyncResponse> disownClientSyncResponse();

  inline bool isSingletonPutRequest();
  inline bool hasSingletonPutRequest();
  inline  ::SingletonPutRequest::Builder getSingletonPutRequest();
  inline void setSingletonPutRequest( ::SingletonPutRequest::Reader value);
  inline  ::SingletonPutRequest::Builder initSingletonPutRequest();
  inline void adoptSingletonPutRequest(::capnp::Orphan< ::SingletonPutRequest>&& value);
  inline ::capnp::Orphan< ::SingletonPutRequest> disownSingletonPutRequest();

  inline bool isDeleteRequest();
  inline bool hasDeleteRequest();
  inline  ::DeleteRequest::Builder getDeleteRequest();
  inline void setDeleteRequest( ::DeleteRequest::Reader value);
  inline  ::DeleteRequest::Builder initDeleteRequest();
  inline void adoptDeleteRequest(::capnp::Orphan< ::DeleteRequest>&& value);
  inline ::capnp::Orphan< ::DeleteRequest> disownDeleteRequest();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Packet::Data::Pipeline {
public:
  typedef Data Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Packets::Reader {
public:
  typedef Packets Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasPackets() const;
  inline  ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Reader getPackets() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Packets::Builder {
public:
  typedef Packets Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasPackets();
  inline  ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Builder getPackets();
  inline void setPackets( ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Builder initPackets(unsigned int size);
  inline void adoptPackets(::capnp::Orphan< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>> disownPackets();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Packets::Pipeline {
public:
  typedef Packets Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool PutRequest::Reader::hasKey() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool PutRequest::Builder::hasKey() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader PutRequest::Reader::getKey() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder PutRequest::Builder::getKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void PutRequest::Builder::setKey( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder PutRequest::Builder::initKey(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void PutRequest::Builder::adoptKey(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> PutRequest::Builder::disownKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool PutRequest::Reader::hasValue() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool PutRequest::Builder::hasValue() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader PutRequest::Reader::getValue() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder PutRequest::Builder::getValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void PutRequest::Builder::setValue( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder PutRequest::Builder::initValue(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void PutRequest::Builder::adoptValue(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> PutRequest::Builder::disownValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline  ::ResponseType PutResponse::Reader::getResponse() const {
  return _reader.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::ResponseType PutResponse::Builder::getResponse() {
  return _builder.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void PutResponse::Builder::setResponse( ::ResponseType value) {
  _builder.setDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool GetRequest::Reader::hasKey() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool GetRequest::Builder::hasKey() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader GetRequest::Reader::getKey() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder GetRequest::Builder::getKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void GetRequest::Builder::setKey( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder GetRequest::Builder::initKey(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void GetRequest::Builder::adoptKey(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> GetRequest::Builder::disownKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::ResponseType GetResponse::Reader::getResponse() const {
  return _reader.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::ResponseType GetResponse::Builder::getResponse() {
  return _builder.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void GetResponse::Builder::setResponse( ::ResponseType value) {
  _builder.setDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool GetResponse::Reader::hasValue() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool GetResponse::Builder::hasValue() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader GetResponse::Reader::getValue() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder GetResponse::Builder::getValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void GetResponse::Builder::setValue( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder GetResponse::Builder::initValue(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void GetResponse::Builder::adoptValue(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> GetResponse::Builder::disownValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::uint64_t RdmaSetupRequest::Reader::getMachineIndex() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t RdmaSetupRequest::Builder::getMachineIndex() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void RdmaSetupRequest::Builder::setMachineIndex( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t RdmaSetupRequest::Reader::getStartAddress() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t RdmaSetupRequest::Builder::getStartAddress() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void RdmaSetupRequest::Builder::setStartAddress( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t RdmaSetupRequest::Reader::getSize() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t RdmaSetupRequest::Builder::getSize() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void RdmaSetupRequest::Builder::setSize( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::ResponseType RdmaSetupResponse::Reader::getResponse() const {
  return _reader.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::ResponseType RdmaSetupResponse::Builder::getResponse() {
  return _builder.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void RdmaSetupResponse::Builder::setResponse( ::ResponseType value) {
  _builder.setDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::ResponseType ClientSyncRequest::Reader::getResponse() const {
  return _reader.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::ResponseType ClientSyncRequest::Builder::getResponse() {
  return _builder.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ClientSyncRequest::Builder::setResponse( ::ResponseType value) {
  _builder.setDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t ClientSyncRequest::Reader::getIndex() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ClientSyncRequest::Builder::getIndex() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void ClientSyncRequest::Builder::setIndex( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::ResponseType ClientSyncResponse::Reader::getResponse() const {
  return _reader.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::ResponseType ClientSyncResponse::Builder::getResponse() {
  return _builder.getDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ClientSyncResponse::Builder::setResponse( ::ResponseType value) {
  _builder.setDataField< ::ResponseType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool SingletonPutRequest::Reader::hasKey() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool SingletonPutRequest::Builder::hasKey() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader SingletonPutRequest::Reader::getKey() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder SingletonPutRequest::Builder::getKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void SingletonPutRequest::Builder::setKey( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder SingletonPutRequest::Builder::initKey(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void SingletonPutRequest::Builder::adoptKey(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> SingletonPutRequest::Builder::disownKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool SingletonPutRequest::Reader::hasValue() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool SingletonPutRequest::Builder::hasValue() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader SingletonPutRequest::Reader::getValue() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder SingletonPutRequest::Builder::getValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void SingletonPutRequest::Builder::setValue( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder SingletonPutRequest::Builder::initValue(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void SingletonPutRequest::Builder::adoptValue(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> SingletonPutRequest::Builder::disownValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool SingletonPutRequest::Reader::getSingleton() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool SingletonPutRequest::Builder::getSingleton() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void SingletonPutRequest::Builder::setSingleton(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t SingletonPutRequest::Reader::getForwardCount() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t SingletonPutRequest::Builder::getForwardCount() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void SingletonPutRequest::Builder::setForwardCount( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline bool DeleteRequest::Reader::hasKey() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool DeleteRequest::Builder::hasKey() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader DeleteRequest::Reader::getKey() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder DeleteRequest::Builder::getKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void DeleteRequest::Builder::setKey( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder DeleteRequest::Builder::initKey(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void DeleteRequest::Builder::adoptKey(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> DeleteRequest::Builder::disownKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline typename Packet::Data::Reader Packet::Reader::getData() const {
  return typename Packet::Data::Reader(_reader);
}
inline typename Packet::Data::Builder Packet::Builder::getData() {
  return typename Packet::Data::Builder(_builder);
}
#if !CAPNP_LITE
inline typename Packet::Data::Pipeline Packet::Pipeline::getData() {
  return typename Packet::Data::Pipeline(_typeless.noop());
}
#endif  // !CAPNP_LITE
inline typename Packet::Data::Builder Packet::Builder::initData() {
  _builder.setDataField< ::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  return typename Packet::Data::Builder(_builder);
}
inline  ::Packet::Data::Which Packet::Data::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::Packet::Data::Which Packet::Data::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool Packet::Data::Reader::isPutRequest() const {
  return which() == Packet::Data::PUT_REQUEST;
}
inline bool Packet::Data::Builder::isPutRequest() {
  return which() == Packet::Data::PUT_REQUEST;
}
inline bool Packet::Data::Reader::hasPutRequest() const {
  if (which() != Packet::Data::PUT_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasPutRequest() {
  if (which() != Packet::Data::PUT_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::PutRequest::Reader Packet::Data::Reader::getPutRequest() const {
  KJ_IREQUIRE((which() == Packet::Data::PUT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PutRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::PutRequest::Builder Packet::Data::Builder::getPutRequest() {
  KJ_IREQUIRE((which() == Packet::Data::PUT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PutRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setPutRequest( ::PutRequest::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::PUT_REQUEST);
  ::capnp::_::PointerHelpers< ::PutRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::PutRequest::Builder Packet::Data::Builder::initPutRequest() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::PUT_REQUEST);
  return ::capnp::_::PointerHelpers< ::PutRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptPutRequest(
    ::capnp::Orphan< ::PutRequest>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::PUT_REQUEST);
  ::capnp::_::PointerHelpers< ::PutRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::PutRequest> Packet::Data::Builder::disownPutRequest() {
  KJ_IREQUIRE((which() == Packet::Data::PUT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PutRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isPutResponse() const {
  return which() == Packet::Data::PUT_RESPONSE;
}
inline bool Packet::Data::Builder::isPutResponse() {
  return which() == Packet::Data::PUT_RESPONSE;
}
inline bool Packet::Data::Reader::hasPutResponse() const {
  if (which() != Packet::Data::PUT_RESPONSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasPutResponse() {
  if (which() != Packet::Data::PUT_RESPONSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::PutResponse::Reader Packet::Data::Reader::getPutResponse() const {
  KJ_IREQUIRE((which() == Packet::Data::PUT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PutResponse>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::PutResponse::Builder Packet::Data::Builder::getPutResponse() {
  KJ_IREQUIRE((which() == Packet::Data::PUT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PutResponse>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setPutResponse( ::PutResponse::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::PUT_RESPONSE);
  ::capnp::_::PointerHelpers< ::PutResponse>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::PutResponse::Builder Packet::Data::Builder::initPutResponse() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::PUT_RESPONSE);
  return ::capnp::_::PointerHelpers< ::PutResponse>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptPutResponse(
    ::capnp::Orphan< ::PutResponse>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::PUT_RESPONSE);
  ::capnp::_::PointerHelpers< ::PutResponse>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::PutResponse> Packet::Data::Builder::disownPutResponse() {
  KJ_IREQUIRE((which() == Packet::Data::PUT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::PutResponse>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isGetRequest() const {
  return which() == Packet::Data::GET_REQUEST;
}
inline bool Packet::Data::Builder::isGetRequest() {
  return which() == Packet::Data::GET_REQUEST;
}
inline bool Packet::Data::Reader::hasGetRequest() const {
  if (which() != Packet::Data::GET_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasGetRequest() {
  if (which() != Packet::Data::GET_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::GetRequest::Reader Packet::Data::Reader::getGetRequest() const {
  KJ_IREQUIRE((which() == Packet::Data::GET_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::GetRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::GetRequest::Builder Packet::Data::Builder::getGetRequest() {
  KJ_IREQUIRE((which() == Packet::Data::GET_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::GetRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setGetRequest( ::GetRequest::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::GET_REQUEST);
  ::capnp::_::PointerHelpers< ::GetRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::GetRequest::Builder Packet::Data::Builder::initGetRequest() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::GET_REQUEST);
  return ::capnp::_::PointerHelpers< ::GetRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptGetRequest(
    ::capnp::Orphan< ::GetRequest>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::GET_REQUEST);
  ::capnp::_::PointerHelpers< ::GetRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::GetRequest> Packet::Data::Builder::disownGetRequest() {
  KJ_IREQUIRE((which() == Packet::Data::GET_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::GetRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isGetResponse() const {
  return which() == Packet::Data::GET_RESPONSE;
}
inline bool Packet::Data::Builder::isGetResponse() {
  return which() == Packet::Data::GET_RESPONSE;
}
inline bool Packet::Data::Reader::hasGetResponse() const {
  if (which() != Packet::Data::GET_RESPONSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasGetResponse() {
  if (which() != Packet::Data::GET_RESPONSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::GetResponse::Reader Packet::Data::Reader::getGetResponse() const {
  KJ_IREQUIRE((which() == Packet::Data::GET_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::GetResponse>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::GetResponse::Builder Packet::Data::Builder::getGetResponse() {
  KJ_IREQUIRE((which() == Packet::Data::GET_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::GetResponse>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setGetResponse( ::GetResponse::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::GET_RESPONSE);
  ::capnp::_::PointerHelpers< ::GetResponse>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::GetResponse::Builder Packet::Data::Builder::initGetResponse() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::GET_RESPONSE);
  return ::capnp::_::PointerHelpers< ::GetResponse>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptGetResponse(
    ::capnp::Orphan< ::GetResponse>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::GET_RESPONSE);
  ::capnp::_::PointerHelpers< ::GetResponse>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::GetResponse> Packet::Data::Builder::disownGetResponse() {
  KJ_IREQUIRE((which() == Packet::Data::GET_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::GetResponse>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isRdmaSetupRequest() const {
  return which() == Packet::Data::RDMA_SETUP_REQUEST;
}
inline bool Packet::Data::Builder::isRdmaSetupRequest() {
  return which() == Packet::Data::RDMA_SETUP_REQUEST;
}
inline bool Packet::Data::Reader::hasRdmaSetupRequest() const {
  if (which() != Packet::Data::RDMA_SETUP_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasRdmaSetupRequest() {
  if (which() != Packet::Data::RDMA_SETUP_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::RdmaSetupRequest::Reader Packet::Data::Reader::getRdmaSetupRequest() const {
  KJ_IREQUIRE((which() == Packet::Data::RDMA_SETUP_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RdmaSetupRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::RdmaSetupRequest::Builder Packet::Data::Builder::getRdmaSetupRequest() {
  KJ_IREQUIRE((which() == Packet::Data::RDMA_SETUP_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RdmaSetupRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setRdmaSetupRequest( ::RdmaSetupRequest::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::RDMA_SETUP_REQUEST);
  ::capnp::_::PointerHelpers< ::RdmaSetupRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::RdmaSetupRequest::Builder Packet::Data::Builder::initRdmaSetupRequest() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::RDMA_SETUP_REQUEST);
  return ::capnp::_::PointerHelpers< ::RdmaSetupRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptRdmaSetupRequest(
    ::capnp::Orphan< ::RdmaSetupRequest>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::RDMA_SETUP_REQUEST);
  ::capnp::_::PointerHelpers< ::RdmaSetupRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::RdmaSetupRequest> Packet::Data::Builder::disownRdmaSetupRequest() {
  KJ_IREQUIRE((which() == Packet::Data::RDMA_SETUP_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RdmaSetupRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isRdmaSetupResponse() const {
  return which() == Packet::Data::RDMA_SETUP_RESPONSE;
}
inline bool Packet::Data::Builder::isRdmaSetupResponse() {
  return which() == Packet::Data::RDMA_SETUP_RESPONSE;
}
inline bool Packet::Data::Reader::hasRdmaSetupResponse() const {
  if (which() != Packet::Data::RDMA_SETUP_RESPONSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasRdmaSetupResponse() {
  if (which() != Packet::Data::RDMA_SETUP_RESPONSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::RdmaSetupResponse::Reader Packet::Data::Reader::getRdmaSetupResponse() const {
  KJ_IREQUIRE((which() == Packet::Data::RDMA_SETUP_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RdmaSetupResponse>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::RdmaSetupResponse::Builder Packet::Data::Builder::getRdmaSetupResponse() {
  KJ_IREQUIRE((which() == Packet::Data::RDMA_SETUP_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RdmaSetupResponse>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setRdmaSetupResponse( ::RdmaSetupResponse::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::RDMA_SETUP_RESPONSE);
  ::capnp::_::PointerHelpers< ::RdmaSetupResponse>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::RdmaSetupResponse::Builder Packet::Data::Builder::initRdmaSetupResponse() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::RDMA_SETUP_RESPONSE);
  return ::capnp::_::PointerHelpers< ::RdmaSetupResponse>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptRdmaSetupResponse(
    ::capnp::Orphan< ::RdmaSetupResponse>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::RDMA_SETUP_RESPONSE);
  ::capnp::_::PointerHelpers< ::RdmaSetupResponse>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::RdmaSetupResponse> Packet::Data::Builder::disownRdmaSetupResponse() {
  KJ_IREQUIRE((which() == Packet::Data::RDMA_SETUP_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RdmaSetupResponse>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isClientSyncRequest() const {
  return which() == Packet::Data::CLIENT_SYNC_REQUEST;
}
inline bool Packet::Data::Builder::isClientSyncRequest() {
  return which() == Packet::Data::CLIENT_SYNC_REQUEST;
}
inline bool Packet::Data::Reader::hasClientSyncRequest() const {
  if (which() != Packet::Data::CLIENT_SYNC_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasClientSyncRequest() {
  if (which() != Packet::Data::CLIENT_SYNC_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::ClientSyncRequest::Reader Packet::Data::Reader::getClientSyncRequest() const {
  KJ_IREQUIRE((which() == Packet::Data::CLIENT_SYNC_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ClientSyncRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::ClientSyncRequest::Builder Packet::Data::Builder::getClientSyncRequest() {
  KJ_IREQUIRE((which() == Packet::Data::CLIENT_SYNC_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ClientSyncRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setClientSyncRequest( ::ClientSyncRequest::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::CLIENT_SYNC_REQUEST);
  ::capnp::_::PointerHelpers< ::ClientSyncRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::ClientSyncRequest::Builder Packet::Data::Builder::initClientSyncRequest() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::CLIENT_SYNC_REQUEST);
  return ::capnp::_::PointerHelpers< ::ClientSyncRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptClientSyncRequest(
    ::capnp::Orphan< ::ClientSyncRequest>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::CLIENT_SYNC_REQUEST);
  ::capnp::_::PointerHelpers< ::ClientSyncRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ClientSyncRequest> Packet::Data::Builder::disownClientSyncRequest() {
  KJ_IREQUIRE((which() == Packet::Data::CLIENT_SYNC_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ClientSyncRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isClientSyncResponse() const {
  return which() == Packet::Data::CLIENT_SYNC_RESPONSE;
}
inline bool Packet::Data::Builder::isClientSyncResponse() {
  return which() == Packet::Data::CLIENT_SYNC_RESPONSE;
}
inline bool Packet::Data::Reader::hasClientSyncResponse() const {
  if (which() != Packet::Data::CLIENT_SYNC_RESPONSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasClientSyncResponse() {
  if (which() != Packet::Data::CLIENT_SYNC_RESPONSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::ClientSyncResponse::Reader Packet::Data::Reader::getClientSyncResponse() const {
  KJ_IREQUIRE((which() == Packet::Data::CLIENT_SYNC_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ClientSyncResponse>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::ClientSyncResponse::Builder Packet::Data::Builder::getClientSyncResponse() {
  KJ_IREQUIRE((which() == Packet::Data::CLIENT_SYNC_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ClientSyncResponse>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setClientSyncResponse( ::ClientSyncResponse::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::CLIENT_SYNC_RESPONSE);
  ::capnp::_::PointerHelpers< ::ClientSyncResponse>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::ClientSyncResponse::Builder Packet::Data::Builder::initClientSyncResponse() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::CLIENT_SYNC_RESPONSE);
  return ::capnp::_::PointerHelpers< ::ClientSyncResponse>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptClientSyncResponse(
    ::capnp::Orphan< ::ClientSyncResponse>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::CLIENT_SYNC_RESPONSE);
  ::capnp::_::PointerHelpers< ::ClientSyncResponse>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::ClientSyncResponse> Packet::Data::Builder::disownClientSyncResponse() {
  KJ_IREQUIRE((which() == Packet::Data::CLIENT_SYNC_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::ClientSyncResponse>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isSingletonPutRequest() const {
  return which() == Packet::Data::SINGLETON_PUT_REQUEST;
}
inline bool Packet::Data::Builder::isSingletonPutRequest() {
  return which() == Packet::Data::SINGLETON_PUT_REQUEST;
}
inline bool Packet::Data::Reader::hasSingletonPutRequest() const {
  if (which() != Packet::Data::SINGLETON_PUT_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasSingletonPutRequest() {
  if (which() != Packet::Data::SINGLETON_PUT_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::SingletonPutRequest::Reader Packet::Data::Reader::getSingletonPutRequest() const {
  KJ_IREQUIRE((which() == Packet::Data::SINGLETON_PUT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::SingletonPutRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::SingletonPutRequest::Builder Packet::Data::Builder::getSingletonPutRequest() {
  KJ_IREQUIRE((which() == Packet::Data::SINGLETON_PUT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::SingletonPutRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setSingletonPutRequest( ::SingletonPutRequest::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::SINGLETON_PUT_REQUEST);
  ::capnp::_::PointerHelpers< ::SingletonPutRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::SingletonPutRequest::Builder Packet::Data::Builder::initSingletonPutRequest() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::SINGLETON_PUT_REQUEST);
  return ::capnp::_::PointerHelpers< ::SingletonPutRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptSingletonPutRequest(
    ::capnp::Orphan< ::SingletonPutRequest>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::SINGLETON_PUT_REQUEST);
  ::capnp::_::PointerHelpers< ::SingletonPutRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::SingletonPutRequest> Packet::Data::Builder::disownSingletonPutRequest() {
  KJ_IREQUIRE((which() == Packet::Data::SINGLETON_PUT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::SingletonPutRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packet::Data::Reader::isDeleteRequest() const {
  return which() == Packet::Data::DELETE_REQUEST;
}
inline bool Packet::Data::Builder::isDeleteRequest() {
  return which() == Packet::Data::DELETE_REQUEST;
}
inline bool Packet::Data::Reader::hasDeleteRequest() const {
  if (which() != Packet::Data::DELETE_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packet::Data::Builder::hasDeleteRequest() {
  if (which() != Packet::Data::DELETE_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::DeleteRequest::Reader Packet::Data::Reader::getDeleteRequest() const {
  KJ_IREQUIRE((which() == Packet::Data::DELETE_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::DeleteRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::DeleteRequest::Builder Packet::Data::Builder::getDeleteRequest() {
  KJ_IREQUIRE((which() == Packet::Data::DELETE_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::DeleteRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::setDeleteRequest( ::DeleteRequest::Reader value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::DELETE_REQUEST);
  ::capnp::_::PointerHelpers< ::DeleteRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::DeleteRequest::Builder Packet::Data::Builder::initDeleteRequest() {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::DELETE_REQUEST);
  return ::capnp::_::PointerHelpers< ::DeleteRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packet::Data::Builder::adoptDeleteRequest(
    ::capnp::Orphan< ::DeleteRequest>&& value) {
  _builder.setDataField<Packet::Data::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Packet::Data::DELETE_REQUEST);
  ::capnp::_::PointerHelpers< ::DeleteRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::DeleteRequest> Packet::Data::Builder::disownDeleteRequest() {
  KJ_IREQUIRE((which() == Packet::Data::DELETE_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::DeleteRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Packets::Reader::hasPackets() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Packets::Builder::hasPackets() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Reader Packets::Reader::getPackets() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Builder Packets::Builder::getPackets() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Packets::Builder::setPackets( ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>::Builder Packets::Builder::initPackets(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Packets::Builder::adoptPackets(
    ::capnp::Orphan< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>> Packets::Builder::disownPackets() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Packet,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}


CAPNP_END_HEADER

